apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME #s-docker-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: my-regitry-key
      containers:
        - name: $APP_NAME
          image: samny91/springboot-docker-pipeline:$IMAGE_NAME
          imagePullPolicy: Always #always fetches new image when the pod start
          ports:
            - containerPort: 8080